### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by pcinereus** [milanglacier/nvim#5]
Hi Milan,
I have been a long time (20+ years) user of emacs (in evil mode 4+ years).  As an ecological statistician, I use it to write all of my R code, LaTeX, quarto, org, bash etc.  However, I do get frustrated by how slow it becomes sometimes (I suspect in part due to font-locking) and particularly while using remotely.  As a result I am considering moving (at least partially) to neovim.  
In exploring many different nvim configs, I came across your repo which seems to align most closely to my needs.  Congrats by the way, I think it is very polished and considered.  However, as a very new neovim user I am struggling with a couple of things.

1. after I start an R REPL, the `<localleader>` key seems unresponsive.  I can still send a line to the REPL via `<leader><leader>ss`, however, this is more keystrokes than I would prefer.  It also means that I dont seem to be able to access all the debug tools etc.  Is there something I am missing?
2. when I use `<leader><leader>ss` to send the current line to the R REPL, it sends the line, but does not then advance to the next line.  Is there a keybinding for this.  In ess-r-mode, this is `C-c C-n`.  I am also not sure how to implement keybinds to send a region or function to the REPL (in ess-r-mode these are `C-c C-r` and `C-c C-f` respectively).

Is this mode, the best way of reaching out to you?

Kind regards

Murray

**Comment by milanglacier** [comment]
Hi, thanks for your compliment for my configs, I am glad that my configs can improve your workflow.

Regarding to your questions:

> however, this is more keystrokes than I would prefer

*you can go to lua/conf/cli_tools.lua and change the keybindings to whatever you like*

>  access all the debug tools

Unfortunately, there are no direct integration with debug tools. The REPL is an external process, without a dedicated package, it is hard to communicate between the R REPL and neovim. (ESS did it, but it is a huge effort). I would simply use the builtin R functions to do the debug, like `browser()`, `debug()`, `debugonce()` etc, and I will do all the works in the R REPL.

You can also look for the `Nvim-R` plugin, which provides some limited support of integration with debugger and neovim. The last time I used it, it can show you the line position of break point and highlight the current line the debug process stopped at, and that's all the integration it had.

>  this is C-c C-n.

There's no keybindings for this command, I never had the need to create this command. However you can create your own bindings trivially, something look like this:

```lua
function(eval_and_next)
vim.cmd 'REPLSendLine' -- you can check the yarepl.nvim to see the complete use case of this command
vim.cmd 'normal! j'
end
```

and bind this function to a keymap.

> send a region or function to the REPL

It is implemented, the command is `REPLSendMotion`, it is bond to `<LocalLeader>s` in my config, the motion/text objects is the vim terminology for "region". I use `nvim-treesitter-textobjects` to get the range of a function, so the key sequence to send a function to the REPL will be `<LocalLeader>saf` (`af` corresponding to the text objects of a function). 

Besides, I highly recommend the **radian** console, it is far more advanced than the vanilla `R` console.

**Comment by pcinereus** [comment]
Brilliant - thanks for your detailed response...

Still not sure why the <localleader> becomes unresponsive after the REPL starts.  This is the sequence I have been trying:
1. open nvim
2. read in a simple R script
3. <localleader>rs or <localleader>r? (and choosing either R or radian)
4. the REPL starts but thereafter the localleader does not do anything

Thanks again

**Comment by milanglacier** [comment]
The keybindings for local leader only works in the R buffer. The keybindings does not work in the REPL buffer. You have to switch back to previous buffer.

**Comment by pcinereus** [comment]
I understand that, and have switched back to the R script buffer (sorry I should have included that in the steps)

**Comment by milanglacier** [comment]
> I understand that, and have switched back to the R script buffer (sorry I should have included that in the steps)

I can't reproduce. Maybe you can share with me something like steps to reproduce (with the key sequence you type), or if possible with video clips (and with key sequence in the video)?

**Comment by pcinereus** [comment]
Good thinking...  I have added an animated gif showing opening an R script, hitting the "\" key to allow start a REPL. moving back to the R script buffer and then attempting to use the "\" key again (nothing happens).  It then shows that if alternatively, I hit SPACE twice, it does work.
Note, the first time I when to make the screencast, I noticed that "\" becomes inactive straight after I first invoke it, regardless of whether I start a REPL or not.  That is if I hit "\" and then cancel out of the menu ("q"), "\" no longer works..

![Peek 2023-10-29 15-30](https://github.com/milanglacier/nvim/assets/16844741/2a9a434b-82e0-44ac-87ba-cd50240e233d)

**Comment by milanglacier** [comment]
I see. Because localleader is remapped to double space in my config, So backslash does not work. 

This is because the complex rules of recursive mapping, or how vim decide to interpret the key sequence of local leader, so sometimes backslash works like double spaces but sometimes not.

so you should always use double spaces rather than backslash.

If you want to change the key, go to basic_settings.lua to change it.

**Comment by pcinereus** [comment]
Great.  I will give that a shot later tonight.  Ta
