### ISSUE TITLE
How to set default colour scheme

### ISSUE THREAD

**Issue by tanc** [milanglacier/nvim#6]
Hi, impressive work! How do I set the default colour scheme on startup to use the dark background and nightfox theme?

**Comment by milanglacier** [comment]
Hi there,

comment out this line:

https://github.com/milanglacier/nvim/blob/ed00123cf297ecbce9adb79d5012b9e82d02aa86/lua/conf/colorscheme.lua#L274

and add two lines in your config:

```lua
vim.o.background = 'dark'
vim.cmd.colorscheme 'nightfox'
```

**Comment by tanc** [comment]
Perfect, thank you!
