### ISSUE TITLE
Can't seem to install Codeium

### ISSUE THREAD

**Issue by tanc** [milanglacier/nvim#7]
I don't know if this is the right place to submit this as it may well be unrelated to your project but I thought I'd start here.

Whenever Codeium tries to run a curl command it fails with `curl error exit_code=23 stderr={ "curl: (23) Failed writing received data to disk/application" }`

At first I thought it was an issue downloading the Codeium server so I downloaded that manually, which got to the authentication stage of running `:Codeium Auth`. After pasting the authentication token and hitting return it throws a similar error:

```
Error executing luv callback:
....local/share/nvim/lazy/plenary.nvim/lua/plenary/curl.lua:289: post https://api.codeium.com/register_user/ - curl error exit_code=23 stderr={ "curl: (23) Failed writing received data to disk/application" }
stack traceback:
        [C]: in function 'error'
        ....local/share/nvim/lazy/plenary.nvim/lua/plenary/curl.lua:289: in function '_user_on_exit'
        .../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:240: in function '_shutdown'
        .../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:47: in function <.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:38>
Press ENTER or type command to continue
```

I've checked permissions on the `~/.cache/nvim/` and `~/.cache/nvim/codeium` directories and my user has read/write access (I also tried setting the folders to `777` but no change).

Any ideas on why this might be happening?

**Comment by milanglacier** [comment]
I guess this is because your curl installation is broken. Try to use another curl.

**Comment by tanc** [comment]
It turns out that the issue was with `XDG_RUNTIME_DIR` pointing to a non existent directory. Fixed by creating the directory and setting ownership. See https://github.com/nvim-lua/plenary.nvim/issues/536#issuecomment-1902572635
